#!/bin/bash
HOOK="$(cd "$(dirname "$0")" && pwd)/block-dangerous-git.sh"
fail=0
t() {
  local expect="$1" cmd="$2"
  local got
  got=$(printf '{"tool_input":{"command":%s}}' "$(jq -Rn --arg c "$cmd" '$c')" | "$HOOK" | jq -r '.hookSpecificOutput.permissionDecision // "allow"')
  [ -z "$got" ] && got=allow
  if [ "$got" = "$expect" ]; then echo "ok    $expect  $cmd"; else echo "FAIL  expected $expect got $got  $cmd"; fail=1; fi
}
t deny  'git push origin main'
t deny  'git push'
t deny  'git -C /tmp push'
t deny  'sudo git push'
t deny  'git status && git reset --hard HEAD~1'
t deny  'git clean -fd'
t deny  'git clean -f'
t deny  'git branch -D foo'
t deny  'git branch -fD foo'
t deny  'git checkout .'
t deny  'git restore . '
t deny  'cd /x && git commit -m "t" && git push -u origin b'
t deny  'x=$(git push 2>&1)'
t deny  'x=`git push`'
t deny  'x="$(git push)"'
t allow 'gh pr create --body "run make && git push"'
t deny  'git push --force-with-lease'
t allow 'git checkout .github/'
t allow 'git restore .env'
t allow 'echo "the hook blocks git push"'
t allow 'git log --grep "git push"'
t allow 'git branch -d foo'
t allow 'git reset --soft HEAD~1'
t allow 'git worktree remove ../wt'
t allow 'git commit -m "feat: x"'
t allow 'git status'
t allow 'grep -r "reset --hard" docs/'
t allow "$(printf 'cat > f <<EOF\n| F14 | hook blocks every `git push` |\nEOF')"
t allow "$(printf 'cat > f <<EOF\nRun the project tests, then: git push happens later\nEOF')"
t deny  'if git push; then echo ok; fi'
t deny  'if true; then :; elif git push; then :; fi'
t deny  'until git push; do sleep 1; done'
t deny  'while git push; do :; done'
t deny  '! git push'
t deny  "$(printf 'grep -q x <<<"hello"\ngit push')"
t deny  "$(printf 'cat <<<hello\ngit reset --hard')"
t deny  '/usr/bin/git push'
t deny  '\git push'
t deny  'sudo -u me git push'
t deny  'timeout -s KILL 30 git push'
t deny  'git -C a\ b push'
t deny  'if git diff --quiet; then git push; fi'
t deny  'for b in a b; do git push origin $b; done'
t deny  '{ git push; }'
t deny  'FOO=1 git push'
t deny  'env FOO=1 git push'
t deny  'timeout 30 git push'
t deny  'git -C "my dir" push'
t deny  'git clean --force'
t deny  'git branch --delete --force foo'
t deny  'git branch -d -f foo'
t deny  'git restore .;git status'
t deny  'git checkout .&&ls'
t deny  'MSG="wip stuff" git push'
t deny  'GIT_COMMITTER_NAME="John Doe" git push'
t deny  "git -c user.name='A B' reset --hard"
t deny  'git -c user.name="A B" push'
t deny  'git --git-dir="a b" push'
t deny  'timeout 1m30s git push'
t deny  'GIT_SSH_COMMAND="ssh -i key" git push'
t allow 'FOO="git push" echo hi'
t allow 'git -c core.pager=cat log -3'
t allow 'git --no-pager log --oneline --grep push'
t allow 'git -P log -S push'
t allow 'git --no-pager diff -- push.ts'
t allow 'git --no-pager grep -n push'
t allow 'git -P show --stat pushover'
t deny  'git --no-pager push'
t deny  'git -C /tmp --no-pager push'
t deny  'git --git-dir=/x/.git push'
t deny  'git --git-dir /x/.git push'
t deny  'git --work-tree /x -C /y push origin main'
t deny  'eval git push'
t deny  'git checkout ./'
t deny  'git restore :/'
t deny  'git checkout -f main'
t deny  'git checkout --force main'
t allow 'git checkout -b feature'
t allow 'git checkout main'
t allow 'cat <<<"$var"'
t allow 'git branch -d foo && git branch -m x y'
t allow 'git diff --quiet || echo dirty'
t allow 'if git diff --quiet; then echo clean; fi'
exit $fail
